//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class GoodsReceiptDetailAvailable
    {
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public int BinLocationID { get; set; }
        public string BinLocationCode { get; set; }
        public string Remarks { get; set; }
        public decimal QuantityAvailable { get; set; }
        public decimal LineVolumeAvailable { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> PackID { get; set; }
        public string PackCode { get; set; }
        public Nullable<int> CartonID { get; set; }
        public string CartonCode { get; set; }
        public Nullable<int> PalletID { get; set; }
        public string PalletCode { get; set; }
        public int GoodsReceiptID { get; set; }
        public int GoodsReceiptDetailID { get; set; }
    }
}
