//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class SalesReturnPendingGoodsIssue
    {
        public int GoodsIssueID { get; set; }
        public string GoodsIssueReference { get; set; }
        public System.DateTime GoodsIssueEntryDate { get; set; }
        public string PrimaryReferences { get; set; }
        public string VoucherCodes { get; set; }
        public string Vehicle { get; set; }
        public string VehicleDriver { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
    }
}
