//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseAdjustmentDetail
    {
        public int WarehouseAdjustmentDetailID { get; set; }
        public int WarehouseAdjustmentID { get; set; }
        public Nullable<int> GoodsReceiptDetailID { get; set; }
        public Nullable<int> GoodsReceiptID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int LocationID { get; set; }
        public int WarehouseID { get; set; }
        public int CommodityID { get; set; }
        public decimal Quantity { get; set; }
        public decimal LineVolume { get; set; }
        public string Remarks { get; set; }
        public bool Approved { get; set; }
    
        public virtual GoodsReceiptDetail GoodsReceiptDetail { get; set; }
        public virtual WarehouseAdjustment WarehouseAdjustment { get; set; }
        public virtual Commodity Commodity { get; set; }
    }
}
